name: build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        release:
          - 25.12.2
        arch:
          - mediatek-filogic
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v6

      - name: Extract package version
        id: get_version
        run: |
          PKG_VERSION=$(grep -r '^PKG_VERSION:=' | cut -d '=' -f2)
          echo "pkg_version=$PKG_VERSION" >> $GITHUB_OUTPUT

      - name: Build package for OpenWRT
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.release }}
          PACKAGES: ntfy
          NO_SHFMT_CHECK: true
          INDEX: 1
          PRIVATE_KEY: ${{ secrets.SIGNKEY }}
          V: w

      - name: Extract public key from signing key
        if: env.HAS_SIGNKEY == 'true'
        env:
          HAS_SIGNKEY: ${{ secrets.SIGNKEY != '' }}
        run: |
          echo "${{ secrets.SIGNKEY }}" | openssl ec -pubout -out openwrt-daxcore.pem

      - name: Upload packages
        uses: actions/upload-artifact@v7
        with:
          name: ntfy-${{ steps.get_version.outputs.pkg_version }}-openwrt-${{ matrix.release }}-${{ matrix.arch }}
          path: bin/packages/**/ntfy*.apk

      - name: Deploy to GitHub Pages
        if: github.ref_type == 'tag'
        run: |
          DEST="deploy/releases/${{ matrix.release }}/${{ matrix.arch }}"
          mkdir -p $DEST
          find bin/packages/ -name "ntfy*.apk" -exec cp {} $DEST/ \;
          find bin/packages/ -name "packages.adb" -exec cp {} $DEST/ \;
          cp openwrt-daxcore.pem deploy/

      - name: Generate Index HTML
        if: github.ref_type == 'tag'
        working-directory: deploy
        run: |
          echo "<html><head><title>OpenWRT Feed</title></head><body>" > index.html
          echo "<h1>Index of OpenWRT Packages</h1><ul>" >> index.html
          # Findet alle Dateien rekursiv und erstellt Links
          find . -type f -not -name "index.html" | sort | sed 's|^\./||' | xargs -I {} echo "<li><a href=\"{}\">{}</a></li>" >> index.html
          echo "</ul></body></html>" >> index.html
          
      - name: Push to Pages Branch
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref_type == 'tag'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          keep_files: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

      - name: Release package
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            bin/packages/**/action/ntfy*.apk
            bin/packages/**/action/packages.adb
            openwrt-daxcore.pem
